---
  
name: ppocr_mobile_v2.0_cls

gops: [0.035707238]
shapes:
  - [1, 3, 48, 192]

mlir_transform:
  model_transform.py 
    --model_name $(name) 
    --model_def $(home)/ch_ppocr_mobile_v2.0_cls_infer.onnx 
    --input_shapes [[1,3,48,192]] 
    --mean 0.0,0.0,0.0 
    --scale 0.0039216,0.0039216,0.0039216 
    --keep_aspect_ratio 
    --pixel_format rgb 
    --output_names softmax_0.tmp_0 
    --test_input $(root)/dataset/samples/dog.jpg 
    --test_result $(workdir)/$(name)_top_outputs.npz 
    --mlir $(workdir)/$(name).mlir
    
#run_calibration.py ch_ppocr_mobile_v2.0_cls_infer.mlir \
#  --dataset ../ILSVRC2012 \
#  --input_num 100 \
#  -o cls_cali_table

deploy:
  - model_deploy.py 
      --mlir $(workdir)/$(name).mlir 
      --quantize F32 
      --chip bm1684x 
      --test_input $(workdir)/$(name)_in_f32.npz 
      --test_reference $(workdir)/$(name)_top_outputs.npz 
      --model $(workdir)/$(name)_1684x_f32.bmodel
      
  - model_deploy.py 
      --mlir $(workdir)/$(name).mlir 
      --quantize INT8 
      --calibration_table $(home)/cls_cali_table 
      --chip bm1684x 
      --test_input $(workdir)/$(name)_in_f32.npz 
      --test_reference $(workdir)/$(name)_top_outputs.npz 
      --tolerance 0.85,0.45 
      --model $(workdir)/$(name)_1684x_int8_sym.bmodel 
  